# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

# Build documentation in the docs/ directory with Sphinx
# To specify the path to the conf.py file, relative to the root of the project,
sphinx:
   configuration: docs/conf.py
   # Can also specify the builder type for the Sphinx documentation, and turn warnings into errors
   # builder: html
   # fail_on_warning: true

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
   - pdf
   - epub
   - htmlzip

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt
   - method: pip
     path: .

# If using a conda environment, 
# add the path to the Conda environment file, relative to the root of the project.
# conda:
#   environment: environment.yml
